### ISSUE TITLE
MSX1/MSX2 lable wrong?

### ISSUE THREAD

**Issue by Yamato-san** [ThreepwoodLeBrush/Names_MiSTer#13]
Hello there,

is there a reason why the more recent MSX1 core by molekula (repository [here](https://github.com/MiSTer-devel/MSX1_MiSTer)) is labled as „MSX1/MSX2“? From my understanding the core supports MSX1 games only. Am I missing something or is the lable mixed up with the older MSX core that asks for VHDs?

Thank you!

**Comment by ThreepwoodLeBrush** [comment]
Dear Yamato-san,

the name change is the result of a discussion with active MSX scene people on the official MiSTer Discord. If you have an account on said Discord you can find the start of the discussion in the general vicinity of this post: https://discord.com/channels/647909397477195803/1056033525922537542/1060960626928779324

To my understanding one of the experts involved in the discussion is also a dev working on the core, which has a switchable MSX2 mode (I have not tried it myself). You can find details on his webpage: https://vampier.net/MSX/

I am not an expert on MSX, so I found it prudent to follow their advice on the naming.

**Comment by Yamato-san** [comment]
Thanks for your help!

That’s awesome to hear. But unfortunately I can not find any switch to turn on MSX2 mode in the menu. From my understanding it is still a test core feature only. Update-All doesn‘t seem to load a MSX2 compatible release.

I hope in will be part of the official repository soon so Update-All will get it. I think the lable „MSX1/MSX2“ is a bit missleading to most users at the moment.

Thanks again!

**Comment by Toryalai1** [comment]
Thats because he hasn't released msx2 support yet. Its wip

**Comment by tdlabac** [comment]
Hi, in the MSX1 project I am currently working on supporting MSX2 as well. I have released several unofficial developer versions to test the capabilities and community reactions. Over time, I discovered the diversity of the MSX world and felt that sticking to specifically selected MSX1 and MSX2 models was a mistake. So I decided to create an environment that will set itself to a specific model according to the uploaded configuration from outside. Since what applies in today's version is different in the next version, I am not making the versions available to the general public. For an idea of how I would like it to work. https://www.youtube.com/watch?v=Qx_9090ODgo

Translated with www.DeepL.com/Translator (free version)

**Comment by ThreepwoodLeBrush** [comment]
For the time being the mention of MSX2 has been removed from the core name. It is now just "MSX1". Once the core supports MSX2 I will change the name again, probably to just "MSX", because it does more justice to the concept used.

Thank you for raising this issue, @Yamato-san, it is much appreciated.
